-- Readable supplier data for Beekeeper / Metabase / plain SQL.
--
-- The answers suppliers actually fill in live in JSONB keyed by field id:
-- ProductPIQ.answers, SupplierProfile.eoiAnswers and .stageAnswers. A database
-- client shows those as one opaque JSON cell per row, so you cannot sort by
-- shelf life, find products missing an HS code, or compare answers across
-- suppliers without hand-writing `answers->>'...'` every time — and the field
-- ids themselves are only documented in TypeScript.
--
-- This migration adds:
--   * "PIQQuestion"     — the question catalogue, mirrored from piq-config.ts
--   * "v_piq_answer"    — one row per answered PIQ question, labelled
--   * "v_supplier_answer" — the same for the EOI + journey stage forms
--
-- Long format (a row per answer) rather than one column per question: it
-- survives questions being added or removed, which a wide view does not.
--
-- Idempotent throughout, for the same reason as
-- 20260808000000_supplier_portal_cms_service_tokens: railway.toml runs
-- `prisma migrate deploy && node dist/server.js`, so any error here stops the
-- API from booting.

-- ---------------------------------------------------------------- catalogue

CREATE TABLE IF NOT EXISTS "PIQQuestion" (
    "id" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "sectionTitle" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL,

    CONSTRAINT "PIQQuestion_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "PIQQuestion_section_position_idx" ON "PIQQuestion"("section", "position");

-- 77 questions from PIQ_GENERAL_CONFIG v1.
-- Generated by afrizonemart-v2/scripts/gen-piq-catalog.mjs — do not hand-edit.
INSERT INTO "PIQQuestion" ("id", "section", "sectionTitle", "label", "type", "required", "position") VALUES
  ('product_name', 'identification', 'Product Identification', 'Product Name', 'text', true, 1),
  ('brand_name', 'identification', 'Product Identification', 'Brand Name', 'text', true, 2),
  ('category', 'identification', 'Product Identification', 'Category', 'select', true, 3),
  ('short_description', 'identification', 'Product Identification', 'Short Description', 'textarea', true, 4),
  ('long_description', 'identification', 'Product Identification', 'Long Description', 'textarea', true, 5),
  ('product_image', 'identification', 'Product Identification', 'Product Image', 'file', true, 6),
  ('packaging_image', 'identification', 'Product Identification', 'Packaging Image', 'file', false, 7),
  ('country_of_origin', 'identification', 'Product Identification', 'Country of Origin', 'select', true, 8),
  ('region_of_origin', 'identification', 'Product Identification', 'State / Province / Region', 'subdivision', true, 9),
  ('gtin', 'identification', 'Product Identification', 'Barcode / GTIN (EAN or UPC)', 'text', false, 10),
  ('hs_code', 'identification', 'Product Identification', 'HS / Tariff Code', 'text', false, 11),
  ('weight_volume', 'specifications', 'Product Specifications', 'Weight / Volume', 'text', true, 12),
  ('dimensions', 'specifications', 'Product Specifications', 'Dimensions (L × W × H)', 'text', false, 13),
  ('units_per_carton', 'specifications', 'Product Specifications', 'Units per carton / case', 'number', false, 14),
  ('carton_specs', 'specifications', 'Product Specifications', 'Carton weight & dimensions', 'text', false, 15),
  ('ingredients', 'specifications', 'Product Specifications', 'Ingredients / Materials', 'textarea', true, 16),
  ('nutritional_content', 'specifications', 'Product Specifications', 'Nutritional Content (if food)', 'textarea', false, 17),
  ('contains', 'specifications', 'Product Specifications', 'Contains (allergens, chemicals, preservatives)', 'textarea', false, 18),
  ('does_not_contain', 'specifications', 'Product Specifications', 'Does Not Contain', 'text', false, 19),
  ('gmo_status', 'specifications', 'Product Specifications', 'GMO Status', 'select', true, 20),
  ('shelf_life', 'specifications', 'Product Specifications', 'Shelf Life / Expiry', 'text', false, 21),
  ('storage_conditions', 'specifications', 'Product Specifications', 'Storage Conditions', 'textarea', true, 22),
  ('has_patent', 'specifications', 'Product Specifications', 'Is there a patent or proprietary protection?', 'boolean', true, 23),
  ('patent_details', 'specifications', 'Product Specifications', 'Patent / IP details', 'textarea', false, 24),
  ('trademark_status', 'specifications', 'Product Specifications', 'Is the product / packaging trademarked or copyrighted?', 'select', true, 25),
  ('how_it_works', 'usage', 'How It Works / Usage', 'How It Works', 'textarea', true, 26),
  ('how_to_use', 'usage', 'How It Works / Usage', 'How to Use It', 'textarea', false, 27),
  ('how_made', 'usage', 'How It Works / Usage', 'How It Is Made', 'textarea', false, 28),
  ('what_it_does', 'usage', 'How It Works / Usage', 'What It Does', 'textarea', false, 29),
  ('what_it_doesnt', 'usage', 'How It Works / Usage', 'What It Doesn’t Do', 'textarea', false, 30),
  ('target_users', 'usage', 'How It Works / Usage', 'Target Users / Audience', 'textarea', true, 31),
  ('general_warning', 'safety', 'Safety, Warnings & Health', 'General Warning', 'textarea', true, 32),
  ('hazardous_materials', 'safety', 'Safety, Warnings & Health', 'Hazardous Materials Present?', 'boolean', true, 33),
  ('sds_upload', 'safety', 'Safety, Warnings & Health', 'Upload Safety Data Sheet (SDS/MSDS)', 'file', false, 34),
  ('cautions', 'safety', 'Safety, Warnings & Health', 'Cautions', 'textarea', true, 35),
  ('allergies', 'safety', 'Safety, Warnings & Health', 'Allergies / Sensitivities', 'textarea', true, 36),
  ('contraindications', 'safety', 'Safety, Warnings & Health', 'Notes for pregnant persons / those on medication / with medical conditions', 'textarea', false, 37),
  ('efficacy_summary', 'safety', 'Safety, Warnings & Health', 'Efficacy Test Results (summary)', 'textarea', false, 38),
  ('efficacy_upload', 'safety', 'Safety, Warnings & Health', 'Efficacy Test Results (upload lab evidence)', 'file', false, 39),
  ('toxicology_upload', 'safety', 'Safety, Warnings & Health', 'Toxicology / Microbial Test (optional)', 'file', false, 40),
  ('afcfta_compliant', 'compliance', 'Certifications & Compliance', 'AfCFTA Compliant?', 'select', true, 41),
  ('agm_compliant', 'compliance', 'Certifications & Compliance', 'AGM Standard Compliant?', 'select', true, 42),
  ('eu_compliant', 'compliance', 'Certifications & Compliance', 'EU Standard Compliant?', 'select', true, 43),
  ('son_certified', 'compliance', 'Certifications & Compliance', 'SON Certification?', 'select', true, 44),
  ('fda_approved', 'compliance', 'Certifications & Compliance', 'FDA Approved?', 'select', true, 45),
  ('halal_certified', 'compliance', 'Certifications & Compliance', 'Halal Certified?', 'select', false, 46),
  ('organic_certified', 'compliance', 'Certifications & Compliance', 'Organic Certified?', 'select', false, 47),
  ('quality_marks', 'compliance', 'Certifications & Compliance', 'Certifications or Quality Marks', 'multiselect', false, 48),
  ('certification_docs', 'compliance', 'Certifications & Compliance', 'Upload Certification Documents', 'file', false, 49),
  ('batch_number', 'traceability', 'Traceability & Sustainability', 'Production Batch / Lot Number', 'text', false, 50),
  ('traceability_statement', 'traceability', 'Traceability & Sustainability', 'Traceability Statement', 'textarea', true, 51),
  ('sourcing_info', 'traceability', 'Traceability & Sustainability', 'Sourcing Information', 'textarea', true, 52),
  ('sustainability_claims', 'traceability', 'Traceability & Sustainability', 'Sustainability Claims', 'textarea', false, 53),
  ('fair_trade', 'traceability', 'Traceability & Sustainability', 'Fair Trade / Ethical Production', 'select', false, 54),
  ('pricing_currency', 'pricing', 'Pricing & Supply', 'Pricing currency', 'select', true, 55),
  ('bulk_price', 'pricing', 'Pricing & Supply', 'Bulk price per unit', 'text', true, 56),
  ('moq', 'pricing', 'Pricing & Supply', 'Minimum Order Quantity (MOQ)', 'number', true, 57),
  ('max_capacity', 'pricing', 'Pricing & Supply', 'Maximum Supply Capacity per Month', 'number', true, 58),
  ('delivery_time', 'pricing', 'Pricing & Supply', 'Expected Delivery Time', 'text', true, 59),
  ('payment_terms', 'pricing', 'Pricing & Supply', 'Payment Terms', 'textarea', true, 60),
  ('incoterms', 'pricing', 'Pricing & Supply', 'Preferred Incoterms', 'select', false, 61),
  ('sample_available', 'pricing', 'Pricing & Supply', 'Are samples available?', 'boolean', false, 62),
  ('sample_price', 'pricing', 'Pricing & Supply', 'Sample price & terms', 'text', false, 63),
  ('brand_story', 'brand', 'Brand & Marketing', 'Brand Story / Origin', 'textarea', true, 64),
  ('usp', 'brand', 'Brand & Marketing', 'Unique Selling Proposition (USP)', 'textarea', true, 65),
  ('comparative_advantage', 'brand', 'Brand & Marketing', 'Product Comparative Advantage', 'textarea', true, 66),
  ('competitive_advantage', 'brand', 'Brand & Marketing', 'Product Competitive Advantage', 'textarea', true, 67),
  ('is_new', 'brand', 'Brand & Marketing', 'Is this product new in the market?', 'boolean', true, 68),
  ('time_in_market', 'brand', 'Brand & Marketing', 'How long has it been in the market?', 'text', true, 69),
  ('where_sold', 'brand', 'Brand & Marketing', 'Where else is the product listed or sold?', 'textarea', true, 70),
  ('differentiators', 'brand', 'Brand & Marketing', 'Key Differentiators / Highlights', 'textarea', true, 71),
  ('target_market', 'brand', 'Brand & Marketing', 'Target Market', 'textarea', true, 72),
  ('promo_materials', 'brand', 'Brand & Marketing', 'Promotional Materials', 'file', false, 73),
  ('social_handles', 'brand', 'Brand & Marketing', 'Social Media Handles / Website', 'text', false, 74),
  ('declaration_agree', 'declaration', 'Declaration & Consent', 'I confirm the information above is true, accurate, and complete.', 'boolean', true, 75),
  ('representative_name', 'declaration', 'Declaration & Consent', 'Full Name of Authorized Representative', 'text', true, 76),
  ('declaration_date', 'declaration', 'Declaration & Consent', 'Date', 'date', true, 77)
ON CONFLICT ("id") DO UPDATE SET
  "section"      = EXCLUDED."section",
  "sectionTitle" = EXCLUDED."sectionTitle",
  "label"        = EXCLUDED."label",
  "type"         = EXCLUDED."type",
  "required"     = EXCLUDED."required",
  "position"     = EXCLUDED."position";

-- -------------------------------------------------------------------- views

-- One row per answered PIQ question, with the question text resolved.
-- Unanswered questions do not appear; use "PIQQuestion" LEFT JOINed to this
-- view when you want the gaps instead.
CREATE OR REPLACE VIEW "v_piq_answer" AS
SELECT
    s."companyName"                                  AS company,
    p.name                                           AS product,
    p.status::text                                   AS piq_status,
    p.completion,
    q."sectionTitle"                                 AS section,
    COALESCE(q.label, a.key)                         AS question,
    CASE jsonb_typeof(a.value)
        WHEN 'string' THEN NULLIF(a.value #>> '{}', '')
        WHEN 'null'   THEN NULL
        WHEN 'array'  THEN NULLIF(
            (SELECT string_agg(e #>> '{}', ' | ') FROM jsonb_array_elements(a.value) e), '')
        ELSE a.value::text
    END                                              AS answer,
    q.required,
    a.key                                            AS question_id,
    q."position"                                     AS question_position,
    p."updatedAt"                                    AS updated_at,
    p.id                                             AS piq_id,
    s.id                                             AS supplier_id
FROM "ProductPIQ" p
JOIN "SupplierProfile" s ON s.id = p."supplierId"
-- CASE guard: jsonb_each() errors on a non-object, so a malformed row would
-- otherwise take out the whole view rather than just itself.
CROSS JOIN LATERAL jsonb_each(
    CASE WHEN jsonb_typeof(p.answers) = 'object' THEN p.answers ELSE '{}'::jsonb END
) AS a(key, value)
LEFT JOIN "PIQQuestion" q ON q.id = a.key;

-- The EOI form and the journey stage forms. stageAnswers is nested one level
-- deeper ({ stage: { field: value } }) than eoiAnswers ({ field: value }), so
-- the two are flattened separately and unioned.
CREATE OR REPLACE VIEW "v_supplier_answer" AS
SELECT
    s."companyName"                                  AS company,
    'Stage ' || st.key                               AS form,
    f.key                                            AS question_id,
    CASE jsonb_typeof(f.value)
        WHEN 'string' THEN NULLIF(f.value #>> '{}', '')
        WHEN 'null'   THEN NULL
        WHEN 'array'  THEN NULLIF(
            (SELECT string_agg(e #>> '{}', ' | ') FROM jsonb_array_elements(f.value) e), '')
        ELSE f.value::text
    END                                              AS answer,
    s."currentStage"                                 AS current_stage,
    s.status::text                                   AS supplier_status,
    s."updatedAt"                                    AS updated_at,
    s.id                                             AS supplier_id
FROM "SupplierProfile" s
CROSS JOIN LATERAL jsonb_each(
    CASE WHEN jsonb_typeof(s."stageAnswers") = 'object' THEN s."stageAnswers" ELSE '{}'::jsonb END
) AS st(key, value)
CROSS JOIN LATERAL jsonb_each(
    CASE WHEN jsonb_typeof(st.value) = 'object' THEN st.value ELSE '{}'::jsonb END
) AS f(key, value)

UNION ALL

SELECT
    s."companyName",
    'EOI',
    f.key,
    CASE jsonb_typeof(f.value)
        WHEN 'string' THEN NULLIF(f.value #>> '{}', '')
        WHEN 'null'   THEN NULL
        WHEN 'array'  THEN NULLIF(
            (SELECT string_agg(e #>> '{}', ' | ') FROM jsonb_array_elements(f.value) e), '')
        ELSE f.value::text
    END,
    s."currentStage",
    s.status::text,
    s."updatedAt",
    s.id
FROM "SupplierProfile" s
CROSS JOIN LATERAL jsonb_each(
    CASE WHEN jsonb_typeof(s."eoiAnswers") = 'object' THEN s."eoiAnswers" ELSE '{}'::jsonb END
) AS f(key, value);

-- ------------------------------------------------------------------- grants

-- azm_readonly is the SELECT-only role humans connect with (see DB_ACCESS.md).
-- It does not exist on every database, so this is conditional rather than a
-- bare GRANT that would abort the migration.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'azm_readonly') THEN
        GRANT SELECT ON "PIQQuestion", "v_piq_answer", "v_supplier_answer" TO azm_readonly;
    END IF;
END $$;
